export const wrestlers = [
  { name: "The Undertaker", image: "/images/undertaker.jpg", rank: 1, chest: 52, biceps: 22, height: 6.10, weight: 309 },
  { name: "Stone Cold Steve Austin", image: "/images/stonecold.jpg", rank: 2, chest: 50, biceps: 21, height: 6.2, weight: 252 },
  { name: "The Rock", image: "/images/therock.jpg", rank: 3, chest: 51, biceps: 21, height: 6.5, weight: 260 },
  { name: "Shawn Michaels", image: "/images/shawnmichaels.jpg", rank: 4, chest: 48, biceps: 19, height: 6.1, weight: 225 },
  { name: "Bret Hart", image: "/images/brethart.jpg", rank: 5, chest: 47, biceps: 18, height: 6.0, weight: 235 },
  { name: "Triple H", image: "/images/tripleh.jpg", rank: 6, chest: 50, biceps: 20, height: 6.4, weight: 255 },
  { name: "Kane", image: "/images/kane.jpg", rank: 7, chest: 54, biceps: 23, height: 7.0, weight: 320 },
  { name: "Mick Foley", image: "/images/mickfoley.jpg", rank: 8, chest: 49, biceps: 19, height: 6.2, weight: 287 },
  { name: "Hulk Hogan", image: "/images/hulkhogan.jpg", rank: 9, chest: 53, biceps: 22, height: 6.7, weight: 302 },
  { name: "Ultimate Warrior", image: "/images/ultimatewarrior.jpg", rank: 10, chest: 52, biceps: 21, height: 6.3, weight: 280 },
  { name: "Ric Flair", image: "/images/ricflair.jpg", rank: 11, chest: 47, biceps: 18, height: 6.1, weight: 243 },
  { name: "Lex Luger", image: "/images/lexluger.jpg", rank: 12, chest: 50, biceps: 20, height: 6.4, weight: 265 },
  { name: "Diesel (Kevin Nash)", image: "/images/diesel.jpg", rank: 13, chest: 52, biceps: 21, height: 6.10, weight: 328 },
  { name: "Razor Ramon", image: "/images/razorramon.jpg", rank: 14, chest: 50, biceps: 20, height: 6.7, weight: 287 },
  { name: "Yokozuna", image: "/images/yokozuna.jpg", rank: 15, chest: 60, biceps: 24, height: 6.4, weight: 589 },
  { name: "British Bulldog", image: "/images/britishbulldog.jpg", rank: 16, chest: 49, biceps: 20, height: 6.0, weight: 260 },
  { name: "Owen Hart", image: "/images/owenhart.jpg", rank: 17, chest: 46, biceps: 18, height: 5.11, weight: 227 },
  { name: "Sid Vicious", image: "/images/sidvicious.jpg", rank: 18, chest: 51, biceps: 21, height: 6.9, weight: 317 },
  { name: "Vader", image: "/images/vader.jpg", rank: 19, chest: 55, biceps: 22, height: 6.5, weight: 450 },
  { name: "Goldust", image: "/images/goldust.jpg", rank: 20, chest: 48, biceps: 19, height: 6.6, weight: 260 },
  { name: "Jeff Jarrett", image: "/images/jeffjarrett.jpg", rank: 21, chest: 46, biceps: 18, height: 6.1, weight: 230 },
  { name: "Tatanka", image: "/images/tatanka.jpg", rank: 22, chest: 47, biceps: 18, height: 6.2, weight: 250 },
  { name: "Doink the Clown", image: "/images/doink.jpg", rank: 23, chest: 45, biceps: 17, height: 6.0, weight: 240 },
  { name: "Mr Perfect", image: "/images/mrperfect.jpg", rank: 24, chest: 47, biceps: 18, height: 6.2, weight: 257 },
  { name: "Jake The Snake Roberts", image: "/images/jakeroberts.jpg", rank: 25, chest: 46, biceps: 18, height: 6.5, weight: 249 },
  { name: "Dusty Rhodes", image: "/images/dustyrhodes.jpg", rank: 26, chest: 48, biceps: 18, height: 6.1, weight: 275 },
  { name: "Jerry Lawler", image: "/images/jerrylawler.jpg", rank: 27, chest: 45, biceps: 17, height: 6.0, weight: 243 },
  { name: "Sgt Slaughter", image: "/images/sgtslaughter.jpg", rank: 28, chest: 47, biceps: 18, height: 6.1, weight: 280 },
  { name: "Big Boss Man", image: "/images/bigbossman.jpg", rank: 29, chest: 48, biceps: 18, height: 6.6, weight: 330 },
  { name: "Rick Rude", image: "/images/rickrude.jpg", rank: 30, chest: 50, biceps: 20, height: 6.3, weight: 252 }
];
